# Generated by Django 5.1.2 on 2024-12-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("date", models.DateField(blank=True, null=True)),
                ("is_expense", models.BooleanField(default=True)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
    ]
