# Generated by Django 5.1.2 on 2024-12-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="is_expense",
        ),
    ]
