import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ExpenseProvider from "./components/Context";
import ThemeToggle from "./components/ThemeToggle";
import GlobalBackground from "./components/GlobalBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="relative flex flex-col min-h-screen">
          <ExpenseProvider>
            <GlobalBackground/>
            <ThemeToggle />
            <main className="flex-1">{children}</main>
          </ExpenseProvider>
        </div>
      </body>
    </html>
  );
}
