# Generated by Django 5.2.4 on 2025-07-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_expense', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.defaultcategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
