# Generated by Django 5.2.4 on 2025-07-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='object_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='content_type',
            new_name='category_type_model',
        ),
    ]
