# Generated by Django 5.2.4 on 2025-08-25 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_user_id_a6db97_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_user_id_cb64ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_status_174464_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_user_id_daa5cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_account_ca6237_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='linked_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(db_index=True, default=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_expense'], name='api_transac_user_id_dbf06d_idx'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
